# Generated by Django 4.2.7 on 2023-11-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.TextField()),
                ("definition", models.TextField()),
                ("example", models.TextField()),
                ("translation", models.TextField()),
                ("pronunciation", models.TextField()),
                ("created", models.DateField()),
            ],
        ),
        migrations.DeleteModel(name="MyModel",),
    ]
