# Generated by Django 4.2.7 on 2023-11-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_word_delete_mymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
